export type MasterDataStorage = 'generic' | 'department' | 'team'
export type MasterDataCodePolicy = 'optional' | 'recommended' | 'required'
export type MasterDataExtraFields = 'none' | 'intake' | 'leadStatus' | 'country' | 'conversationChannel'

export type MasterDataCategory = {
  key: string
  name: string
  group: string
  storage: MasterDataStorage
  codePolicy: MasterDataCodePolicy
  parentCategoryKey?: string
  extraFields: MasterDataExtraFields
}

export type MasterDataSeed = {
  categoryKey: string
  name: string
  code: string
  description?: string
  sortOrder: number
  isSystem?: boolean
  behaviorKey?: string
  parentCode?: string
  extras?: Record<string, string>
}

export const MASTER_DATA_CATEGORIES: MasterDataCategory[] = [
  { key: 'LEAD_SOURCE', name: 'Lead Source', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_CHANNEL', name: 'Lead Channel', group: 'Lead Management', storage: 'generic', codePolicy: 'required', parentCategoryKey: 'LEAD_SOURCE', extraFields: 'none' },
  { key: 'LEAD_STATUS', name: 'Lead Status', group: 'Lead Management', storage: 'generic', codePolicy: 'required', extraFields: 'leadStatus' },
  { key: 'LEAD_TYPE', name: 'Lead Type', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_PRIORITY', name: 'Lead Priority', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_QUALITY', name: 'Lead Quality', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_LOST_REASON', name: 'Lead Lost Reason', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'LEAD_CLOSE_REASON', name: 'Lead Close Reason', group: 'Lead Management', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'QUALIFICATION_RESULT', name: 'Qualification Result', group: 'Lead Qualification', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'UNQUALIFIED_REASON', name: 'Unqualified Reason', group: 'Lead Qualification', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'QUALIFICATION_FIT', name: 'Qualification Fit', group: 'Lead Qualification', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'BUDGET_RANGE', name: 'Estimated Budget', group: 'Lead Qualification', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'FUNDING_SOURCE', name: 'Funding Source', group: 'Lead Qualification', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'FINANCIAL_READINESS', name: 'Financial Readiness', group: 'Lead Qualification', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DECISION_TIMELINE', name: 'Decision Timeline', group: 'Lead Intent', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DECISION_MAKER', name: 'Decision Maker', group: 'Lead Intent', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'APPLICATION_READINESS', name: 'Application Readiness', group: 'Lead Intent', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'STUDY_INTENT', name: 'Study Intent', group: 'Lead Intent', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'EDUCATION_LEVEL', name: 'Education Level', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'ACADEMIC_BACKGROUND', name: 'Academic Background', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'SUBJECT_FIELD', name: 'Subject/Field of Study', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'GRADING_SYSTEM', name: 'Grading System', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'ENGLISH_TEST_TYPE', name: 'English Test Type', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'TEST_STATUS', name: 'Test Status', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'ENGLISH_PROFICIENCY_LEVEL', name: 'English Proficiency Level', group: 'Academic', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'COUNTRY', name: 'Country', group: 'Study Abroad', storage: 'generic', codePolicy: 'required', extraFields: 'country' },
  { key: 'STATE_PROVINCE', name: 'State/Province', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'COUNTRY', extraFields: 'none' },
  { key: 'CITY', name: 'City', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'STATE_PROVINCE', extraFields: 'none' },
  { key: 'INTAKE', name: 'Intake', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', extraFields: 'intake' },
  { key: 'UNIVERSITY', name: 'University', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'COUNTRY', extraFields: 'none' },
  { key: 'COURSE_PROGRAM', name: 'Course/Program', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'UNIVERSITY', extraFields: 'none' },
  { key: 'STUDY_LEVEL', name: 'Study Level', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'STUDY_PURPOSE', name: 'Study Purpose', group: 'Study Abroad', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'SERVICE_CATEGORY', name: 'Service Category', group: 'Service', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'SERVICE_TYPE', name: 'Service Type', group: 'Service', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'SERVICE_CATEGORY', extraFields: 'none' },
  { key: 'PACKAGE_TYPE', name: 'Package Type', group: 'Service', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'CHARGE_TYPE', name: 'Charge Type', group: 'Service', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DISCOUNT_TYPE', name: 'Discount Type', group: 'Service', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'ACTIVITY_TYPE', name: 'Activity Type', group: 'Communication', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'FOLLOW_UP_TYPE', name: 'Follow-up Type', group: 'Communication', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'CONVERSATION_CHANNEL', name: 'Note Channel', group: 'Communication', storage: 'generic', codePolicy: 'required', extraFields: 'conversationChannel' },
  { key: 'CONTACT_METHOD', name: 'Contact Method', group: 'Communication', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'CONTACT_TIME', name: 'Contact Time', group: 'Communication', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'CONTACT_RESULT', name: 'Contact Result', group: 'Communication', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DEPARTMENT', name: 'Department', group: 'Employee', storage: 'department', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'TEAM', name: 'Team', group: 'Employee', storage: 'team', codePolicy: 'recommended', parentCategoryKey: 'DEPARTMENT', extraFields: 'none' },
  { key: 'DESIGNATION', name: 'Designation', group: 'Employee', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'EMPLOYMENT_TYPE', name: 'Employment Type', group: 'Employee', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'EMPLOYMENT_STATUS', name: 'Employment Status', group: 'Employee', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DOCUMENT_CATEGORY', name: 'Document Category', group: 'Documents', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DOCUMENT_TYPE', name: 'Document Type', group: 'Documents', storage: 'generic', codePolicy: 'recommended', parentCategoryKey: 'DOCUMENT_CATEGORY', extraFields: 'none' },
  { key: 'DOCUMENT_STATUS', name: 'Document Status', group: 'Documents', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'REJECTION_REASON', name: 'Rejection Reason', group: 'Documents', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'DOCUMENT_REQUEST_METHOD', name: 'Document Request Method', group: 'Documents', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'PAYMENT_METHOD', name: 'Payment Method', group: 'Payment', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'PAYMENT_TYPE', name: 'Payment Type', group: 'Payment', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'PAYMENT_STATUS', name: 'Payment Status', group: 'Payment', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
  { key: 'REFUND_REASON', name: 'Refund Reason', group: 'Payment', storage: 'generic', codePolicy: 'recommended', extraFields: 'none' },
]

export const MASTER_DATA_CATEGORY_MAP = new Map(MASTER_DATA_CATEGORIES.map((item) => [item.key, item]))

export const MASTER_DATA_SEEDS: MasterDataSeed[] = [
  { categoryKey: 'LEAD_SOURCE', name: 'Meta', code: 'META', sortOrder: 1 },
  { categoryKey: 'LEAD_SOURCE', name: 'Facebook Lead Ads', code: 'FACEBOOK_LEAD_ADS', sortOrder: 10, isSystem: true, description: 'System source for Facebook Lead Ads. Not editable on the lead.' },
  { categoryKey: 'LEAD_SOURCE', name: 'Instagram Lead Ads', code: 'INSTAGRAM_LEAD_ADS', sortOrder: 11, isSystem: true, description: 'System source for Instagram Lead Ads. Not editable on the lead.' },
  { categoryKey: 'LEAD_SOURCE', name: 'Website', code: 'WEBSITE', sortOrder: 2 },
  { categoryKey: 'LEAD_SOURCE', name: 'WhatsApp', code: 'WHATSAPP', sortOrder: 3 },
  { categoryKey: 'LEAD_SOURCE', name: 'Email', code: 'EMAIL', sortOrder: 4 },
  { categoryKey: 'LEAD_SOURCE', name: 'Referral', code: 'REFERRAL', sortOrder: 5 },
  { categoryKey: 'LEAD_SOURCE', name: 'Walk-in', code: 'WALK_IN', sortOrder: 6 },
  { categoryKey: 'LEAD_SOURCE', name: 'Phone Call', code: 'PHONE', sortOrder: 7 },
  { categoryKey: 'LEAD_SOURCE', name: 'Manual Entry', code: 'MANUAL_ENTRY', sortOrder: 8 },
  { categoryKey: 'LEAD_SOURCE', name: 'Existing Client', code: 'EXISTING_CLIENT', sortOrder: 9 },
  { categoryKey: 'LEAD_SOURCE', name: 'Campaign', code: 'CAMPAIGN', sortOrder: 12 },
  { categoryKey: 'LEAD_SOURCE', name: 'Other', code: 'OTHER', sortOrder: 13 },
  { categoryKey: 'LEAD_CHANNEL', name: 'Website Contact Form', code: 'WEBSITE_FORM', sortOrder: 1, parentCode: 'WEBSITE', isSystem: true },
  { categoryKey: 'LEAD_CHANNEL', name: 'Website Organic', code: 'ORGANIC', sortOrder: 2, parentCode: 'WEBSITE' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Direct Entry', code: 'DIRECT', sortOrder: 3, parentCode: 'WEBSITE' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Google Ads', code: 'GOOGLE_ADS', sortOrder: 4, parentCode: 'WEBSITE' },
  { categoryKey: 'LEAD_CHANNEL', name: 'YouTube Ads', code: 'YOUTUBE_ADS', sortOrder: 5, parentCode: 'WEBSITE' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Facebook Lead Form', code: 'FACEBOOK_LEAD_FORM', sortOrder: 1, parentCode: 'META', isSystem: true },
  { categoryKey: 'LEAD_CHANNEL', name: 'Instagram Lead Form', code: 'INSTAGRAM_LEAD_FORM', sortOrder: 2, parentCode: 'META', isSystem: true },
  { categoryKey: 'LEAD_CHANNEL', name: 'Facebook Ads', code: 'FACEBOOK_ADS', sortOrder: 3, parentCode: 'META' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Instagram Ads', code: 'INSTAGRAM_ADS', sortOrder: 4, parentCode: 'META' },
  { categoryKey: 'LEAD_CHANNEL', name: 'WhatsApp Conversation', code: 'WHATSAPP_CONVERSATION', sortOrder: 1, parentCode: 'WHATSAPP', isSystem: true },
  { categoryKey: 'LEAD_CHANNEL', name: 'Email Message', code: 'EMAIL_MESSAGE', sortOrder: 1, parentCode: 'EMAIL', isSystem: true },
  { categoryKey: 'LEAD_CHANNEL', name: 'Referral', code: 'REFERRAL', sortOrder: 1, parentCode: 'REFERRAL' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Walk-in', code: 'WALK_IN', sortOrder: 1, parentCode: 'WALK_IN' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Phone Call', code: 'PHONE_CALL', sortOrder: 1, parentCode: 'PHONE' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Manual Phone Call', code: 'MANUAL_PHONE', sortOrder: 1, parentCode: 'MANUAL_ENTRY' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Manual Walk-in', code: 'MANUAL_WALK_IN', sortOrder: 2, parentCode: 'MANUAL_ENTRY' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Existing Client', code: 'EXISTING_CLIENT', sortOrder: 1, parentCode: 'EXISTING_CLIENT' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Partner Campaign', code: 'PARTNER', sortOrder: 1, parentCode: 'OTHER' },
  { categoryKey: 'LEAD_CHANNEL', name: 'Unmapped', code: 'UNMAPPED', sortOrder: 2, parentCode: 'OTHER', isSystem: true },
  { categoryKey: 'LEAD_STATUS', name: 'New', code: 'NEW', sortOrder: 1, isSystem: true, description: 'Newly created lead. No action has been taken yet.' },
  { categoryKey: 'LEAD_STATUS', name: 'Contacted', code: 'CONTACTED', sortOrder: 2, description: 'Initial communication has been completed.' },
  { categoryKey: 'LEAD_STATUS', name: 'Qualified', code: 'QUALIFIED', sortOrder: 3, description: 'Lead has met qualification criteria.' },
  { categoryKey: 'LEAD_STATUS', name: 'Counselling', code: 'COUNSELLING', sortOrder: 4, description: 'Counsellor is actively working with the student on requirements and study options.' },
  { categoryKey: 'LEAD_STATUS', name: 'Offered', code: 'OFFERED', sortOrder: 5, description: 'A Service/Package offer has been made to the student.' },
  { categoryKey: 'LEAD_STATUS', name: 'Converted', code: 'CONVERTED', sortOrder: 6, isSystem: true, behaviorKey: 'converted', description: 'The student has agreed to take the service. Distinct from File Opened.' },
  { categoryKey: 'LEAD_STATUS', name: 'File Opening Pending', code: 'FILE_OPENING_PENDING', sortOrder: 7, isSystem: true, behaviorKey: 'file_opening_pending', description: 'Conversion has occurred but File Opening is not yet complete.' },
  { categoryKey: 'LEAD_STATUS', name: 'File Opened', code: 'FILE_OPENED', sortOrder: 8, isSystem: true, behaviorKey: 'file_opened', description: 'The CRM File has been successfully created.' },
  { categoryKey: 'LEAD_STATUS', name: 'Lost', code: 'LOST', sortOrder: 9, isSystem: true, behaviorKey: 'lost', description: 'The business opportunity has been lost. A Lost Reason is mandatory.' },
  { categoryKey: 'LEAD_STATUS', name: 'Closed', code: 'CLOSED', sortOrder: 10, isSystem: true, behaviorKey: 'closed', description: 'The Lead lifecycle has been permanently closed for reasons other than Lost.' },
  { categoryKey: 'LEAD_STATUS', name: 'Duplicate', code: 'DUPLICATE', sortOrder: 11, isSystem: true, behaviorKey: 'duplicate', description: 'Identified as a duplicate of an existing Lead.' },
  { categoryKey: 'LEAD_STATUS', name: 'Invalid', code: 'INVALID', sortOrder: 12, isSystem: true, behaviorKey: 'invalid', description: 'Identified as a non-genuine/invalid Lead.' },
  { categoryKey: 'LEAD_TYPE', name: 'Student', code: 'STUDENT', sortOrder: 1 },
  { categoryKey: 'LEAD_TYPE', name: 'Guardian', code: 'GUARDIAN', sortOrder: 2 },
  { categoryKey: 'LEAD_PRIORITY', name: 'High', code: 'HIGH', sortOrder: 1 },
  { categoryKey: 'LEAD_PRIORITY', name: 'Medium', code: 'MEDIUM', sortOrder: 2 },
  { categoryKey: 'LEAD_PRIORITY', name: 'Low', code: 'LOW', sortOrder: 3 },
  { categoryKey: 'LEAD_QUALITY', name: 'Hot', code: 'HOT', sortOrder: 1 },
  { categoryKey: 'LEAD_QUALITY', name: 'Warm', code: 'WARM', sortOrder: 2 },
  { categoryKey: 'LEAD_QUALITY', name: 'Cold', code: 'COLD', sortOrder: 3 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Price', code: 'PRICE', sortOrder: 1 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Not Interested', code: 'NOT_INTERESTED', sortOrder: 2 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'No Response', code: 'NO_RESPONSE', sortOrder: 3 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Competitor', code: 'COMPETITOR', sortOrder: 4 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Timing', code: 'TIMING', sortOrder: 5 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Wrong Lead', code: 'WRONG_LEAD', sortOrder: 6 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Eligibility Issue', code: 'ELIGIBILITY', sortOrder: 7 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Chose Another Consultancy', code: 'OTHER_CONSULTANCY', sortOrder: 8 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Contact Not Reachable', code: 'NOT_REACHABLE', sortOrder: 9 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Intake Missed', code: 'INTAKE_MISSED', sortOrder: 10 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Country Changed', code: 'COUNTRY_CHANGED', sortOrder: 11 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Duplicate', code: 'DUPLICATE', sortOrder: 12 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Invalid', code: 'INVALID', sortOrder: 13 },
  { categoryKey: 'LEAD_LOST_REASON', name: 'Other', code: 'OTHER', sortOrder: 14 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Business Decision', code: 'BUSINESS_DECISION', sortOrder: 1 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Not Interested', code: 'NOT_INTERESTED', sortOrder: 2 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Duplicate', code: 'DUPLICATE', sortOrder: 3 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Invalid Lead', code: 'INVALID', sortOrder: 4 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Service Not Available', code: 'UNAVAILABLE', sortOrder: 5 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Student Withdrew', code: 'WITHDREW', sortOrder: 6 },
  { categoryKey: 'LEAD_CLOSE_REASON', name: 'Other', code: 'OTHER', sortOrder: 7 },
  { categoryKey: 'QUALIFICATION_RESULT', name: 'Qualified', code: 'QUALIFIED', sortOrder: 1 },
  { categoryKey: 'QUALIFICATION_RESULT', name: 'Potential', code: 'POTENTIAL', sortOrder: 2 },
  { categoryKey: 'QUALIFICATION_RESULT', name: 'Unqualified', code: 'UNQUALIFIED', sortOrder: 3 },
  { categoryKey: 'UNQUALIFIED_REASON', name: 'Academic Requirement', code: 'ACADEMIC', sortOrder: 1 },
  { categoryKey: 'UNQUALIFIED_REASON', name: 'Financial Issue', code: 'FINANCIAL', sortOrder: 2 },
  { categoryKey: 'UNQUALIFIED_REASON', name: 'English Requirement', code: 'ENGLISH', sortOrder: 3 },
  { categoryKey: 'UNQUALIFIED_REASON', name: 'Intake Issue', code: 'INTAKE', sortOrder: 4 },
  { categoryKey: 'UNQUALIFIED_REASON', name: 'Country Requirement', code: 'COUNTRY', sortOrder: 5 },
  { categoryKey: 'UNQUALIFIED_REASON', name: 'Other', code: 'OTHER', sortOrder: 6 },
  { categoryKey: 'QUALIFICATION_FIT', name: 'Strong', code: 'STRONG', sortOrder: 1 },
  { categoryKey: 'QUALIFICATION_FIT', name: 'Good Fit', code: 'GOOD', sortOrder: 2 },
  { categoryKey: 'QUALIFICATION_FIT', name: 'Average', code: 'AVERAGE', sortOrder: 3 },
  { categoryKey: 'QUALIFICATION_FIT', name: 'Weak', code: 'WEAK', sortOrder: 4 },
  { categoryKey: 'BUDGET_RANGE', name: 'Below BDT 10 Lac', code: 'BELOW_10L', sortOrder: 1 },
  { categoryKey: 'BUDGET_RANGE', name: 'BDT 10–20 Lac', code: '10_20L', sortOrder: 2 },
  { categoryKey: 'BUDGET_RANGE', name: 'BDT 20–30 Lac', code: '20_30L', sortOrder: 3 },
  { categoryKey: 'BUDGET_RANGE', name: 'BDT 30–50 Lac', code: '30_50L', sortOrder: 4 },
  { categoryKey: 'BUDGET_RANGE', name: 'BDT 50 Lac+', code: '50L_PLUS', sortOrder: 5 },
  { categoryKey: 'BUDGET_RANGE', name: 'Unknown', code: 'UNKNOWN', sortOrder: 6 },
  { categoryKey: 'FUNDING_SOURCE', name: 'Self', code: 'SELF', sortOrder: 1 },
  { categoryKey: 'FUNDING_SOURCE', name: 'Family', code: 'FAMILY', sortOrder: 2 },
  { categoryKey: 'FUNDING_SOURCE', name: 'Sponsor', code: 'SPONSOR', sortOrder: 3 },
  { categoryKey: 'FUNDING_SOURCE', name: 'Education Loan', code: 'LOAN', sortOrder: 4 },
  { categoryKey: 'FUNDING_SOURCE', name: 'Other', code: 'OTHER', sortOrder: 5 },
  { categoryKey: 'FUNDING_SOURCE', name: 'Unknown', code: 'UNKNOWN', sortOrder: 6 },
  { categoryKey: 'FINANCIAL_READINESS', name: 'Ready', code: 'READY', sortOrder: 1 },
  { categoryKey: 'FINANCIAL_READINESS', name: 'Partially Ready', code: 'PARTIAL', sortOrder: 2 },
  { categoryKey: 'FINANCIAL_READINESS', name: 'Not Ready', code: 'NOT_READY', sortOrder: 3 },
  { categoryKey: 'FINANCIAL_READINESS', name: 'Unknown', code: 'UNKNOWN', sortOrder: 4 },
  { categoryKey: 'DECISION_TIMELINE', name: 'Immediate', code: 'IMMEDIATE', sortOrder: 1 },
  { categoryKey: 'DECISION_TIMELINE', name: 'Within 1–3 Months', code: '1_3_MONTHS', sortOrder: 2 },
  { categoryKey: 'DECISION_TIMELINE', name: 'Within 3–6 Months', code: '3_6_MONTHS', sortOrder: 3 },
  { categoryKey: 'DECISION_TIMELINE', name: '6+ Months', code: '6_PLUS_MONTHS', sortOrder: 4 },
  { categoryKey: 'DECISION_TIMELINE', name: 'Just Exploring', code: 'EXPLORING', sortOrder: 5 },
  { categoryKey: 'DECISION_MAKER', name: 'Student', code: 'STUDENT', sortOrder: 1 },
  { categoryKey: 'DECISION_MAKER', name: 'Parents', code: 'PARENTS', sortOrder: 2 },
  { categoryKey: 'DECISION_MAKER', name: 'Student + Parents', code: 'STUDENT_PARENTS', sortOrder: 3 },
  { categoryKey: 'DECISION_MAKER', name: 'Spouse/Family', code: 'SPOUSE_FAMILY', sortOrder: 4 },
  { categoryKey: 'DECISION_MAKER', name: 'Other', code: 'OTHER', sortOrder: 5 },
  { categoryKey: 'APPLICATION_READINESS', name: 'Ready Now', code: 'READY_NOW', sortOrder: 1 },
  { categoryKey: 'APPLICATION_READINESS', name: 'Planning', code: 'PLANNING', sortOrder: 2 },
  { categoryKey: 'APPLICATION_READINESS', name: 'Exploring', code: 'EXPLORING', sortOrder: 3 },
  { categoryKey: 'STUDY_INTENT', name: 'High', code: 'HIGH', sortOrder: 1 },
  { categoryKey: 'STUDY_INTENT', name: 'Medium', code: 'MEDIUM', sortOrder: 2 },
  { categoryKey: 'STUDY_INTENT', name: 'Low', code: 'LOW', sortOrder: 3 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'SSC / O-Level', code: 'SSC', sortOrder: 1 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'HSC / A-Level', code: 'HSC', sortOrder: 2 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'Diploma', code: 'DIPLOMA', sortOrder: 3 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'Bachelor', code: 'BACHELOR', sortOrder: 4 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'Master', code: 'MASTER', sortOrder: 5 },
  { categoryKey: 'EDUCATION_LEVEL', name: 'PhD', code: 'PHD', sortOrder: 6 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Science', code: 'SCIENCE', sortOrder: 1 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Commerce', code: 'COMMERCE', sortOrder: 2 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Arts / Humanities', code: 'ARTS', sortOrder: 3 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Engineering', code: 'ENGINEERING', sortOrder: 4 },
  { categoryKey: 'ACADEMIC_BACKGROUND', name: 'Business Studies', code: 'BUSINESS', sortOrder: 5 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Computer Science', code: 'CS', sortOrder: 1 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Business Administration', code: 'BBA', sortOrder: 2 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Accounting & Finance', code: 'AF', sortOrder: 3 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Nursing', code: 'NURSING', sortOrder: 4 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Civil Engineering', code: 'CIVIL', sortOrder: 5 },
  { categoryKey: 'SUBJECT_FIELD', name: 'Data Science', code: 'DATA_SCIENCE', sortOrder: 6 },
  { categoryKey: 'GRADING_SYSTEM', name: 'GPA (4.0)', code: 'GPA_4', sortOrder: 1 },
  { categoryKey: 'GRADING_SYSTEM', name: 'GPA (5.0)', code: 'GPA_5', sortOrder: 2 },
  { categoryKey: 'GRADING_SYSTEM', name: 'Percentage', code: 'PERCENT', sortOrder: 3 },
  { categoryKey: 'GRADING_SYSTEM', name: 'CGPA', code: 'CGPA', sortOrder: 4 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'IELTS', code: 'IELTS', sortOrder: 1 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'TOEFL', code: 'TOEFL', sortOrder: 2 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'PTE', code: 'PTE', sortOrder: 3 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'Duolingo', code: 'DUOLINGO', sortOrder: 4 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'Other', code: 'OTHER', sortOrder: 5 },
  { categoryKey: 'ENGLISH_TEST_TYPE', name: 'None', code: 'NONE', sortOrder: 6 },
  { categoryKey: 'TEST_STATUS', name: 'Test Taken', code: 'TAKEN', sortOrder: 1 },
  { categoryKey: 'TEST_STATUS', name: 'Preparing', code: 'PREPARING', sortOrder: 2 },
  { categoryKey: 'TEST_STATUS', name: 'Not Started', code: 'NOT_STARTED', sortOrder: 3 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'Beginner', code: 'BEGINNER', sortOrder: 1 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'Intermediate', code: 'INTERMEDIATE', sortOrder: 2 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'Advanced', code: 'ADVANCED', sortOrder: 3 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'IELTS 6.0', code: 'IELTS_60', sortOrder: 4 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'IELTS 6.5', code: 'IELTS_65', sortOrder: 5 },
  { categoryKey: 'ENGLISH_PROFICIENCY_LEVEL', name: 'IELTS 7.0', code: 'IELTS_70', sortOrder: 6 },
  { categoryKey: 'COUNTRY', name: 'Canada', code: 'CA', sortOrder: 1, extras: { fileOpeningCharge: '2000.00' } },
  { categoryKey: 'COUNTRY', name: 'United Kingdom', code: 'UK', sortOrder: 2, extras: { fileOpeningCharge: '1500.00' } },
  { categoryKey: 'COUNTRY', name: 'Australia', code: 'AU', sortOrder: 3, extras: { fileOpeningCharge: '2500.00' } },
  { categoryKey: 'COUNTRY', name: 'USA', code: 'US', sortOrder: 4 },
  { categoryKey: 'COUNTRY', name: 'Germany', code: 'DE', sortOrder: 5 },
  { categoryKey: 'STATE_PROVINCE', name: 'Ontario', code: 'ON', sortOrder: 1, parentCode: 'CA' },
  { categoryKey: 'STATE_PROVINCE', name: 'Alberta', code: 'AB', sortOrder: 2, parentCode: 'CA' },
  { categoryKey: 'STATE_PROVINCE', name: 'British Columbia', code: 'BC', sortOrder: 3, parentCode: 'CA' },
  { categoryKey: 'STATE_PROVINCE', name: 'England', code: 'ENG', sortOrder: 4, parentCode: 'UK' },
  { categoryKey: 'STATE_PROVINCE', name: 'New South Wales', code: 'NSW', sortOrder: 5, parentCode: 'AU' },
  { categoryKey: 'CITY', name: 'Toronto', code: 'TORONTO', sortOrder: 1, parentCode: 'ON' },
  { categoryKey: 'CITY', name: 'Ottawa', code: 'OTTAWA', sortOrder: 2, parentCode: 'ON' },
  { categoryKey: 'CITY', name: 'Calgary', code: 'CALGARY', sortOrder: 3, parentCode: 'AB' },
  { categoryKey: 'CITY', name: 'Vancouver', code: 'VANCOUVER', sortOrder: 4, parentCode: 'BC' },
  { categoryKey: 'CITY', name: 'London', code: 'LONDON', sortOrder: 5, parentCode: 'ENG' },
  { categoryKey: 'CITY', name: 'Sydney', code: 'SYDNEY', sortOrder: 6, parentCode: 'NSW' },
  { categoryKey: 'INTAKE', name: 'January 2027', code: 'JAN_2027', sortOrder: 1, extras: { startDate: '2027-01-01', endDate: '2027-01-31' } },
  { categoryKey: 'INTAKE', name: 'May 2027', code: 'MAY_2027', sortOrder: 2, extras: { startDate: '2027-05-01', endDate: '2027-05-31' } },
  { categoryKey: 'INTAKE', name: 'September 2027', code: 'SEP_2027', sortOrder: 3, extras: { startDate: '2027-09-01', endDate: '2027-09-30' } },
  { categoryKey: 'INTAKE', name: 'January 2028', code: 'JAN_2028', sortOrder: 4, extras: { startDate: '2028-01-01', endDate: '2028-01-31' } },
  { categoryKey: 'UNIVERSITY', name: 'University of Toronto', code: 'UOT', sortOrder: 1, parentCode: 'CA' },
  { categoryKey: 'UNIVERSITY', name: 'University of Alberta', code: 'UOA', sortOrder: 2, parentCode: 'CA' },
  { categoryKey: 'UNIVERSITY', name: 'McGill University', code: 'MCGILL', sortOrder: 3, parentCode: 'CA' },
  { categoryKey: 'UNIVERSITY', name: 'University of British Columbia', code: 'UBC', sortOrder: 4, parentCode: 'CA' },
  { categoryKey: 'UNIVERSITY', name: 'University of Manchester', code: 'UOM', sortOrder: 5, parentCode: 'UK' },
  { categoryKey: 'UNIVERSITY', name: 'University of Sydney', code: 'USYD', sortOrder: 6, parentCode: 'AU' },
  { categoryKey: 'COURSE_PROGRAM', name: 'Computer Science', code: 'CS', sortOrder: 1, parentCode: 'UOT' },
  { categoryKey: 'COURSE_PROGRAM', name: 'Software Engineering', code: 'SE', sortOrder: 2, parentCode: 'UOT' },
  { categoryKey: 'COURSE_PROGRAM', name: 'Business Administration', code: 'BBA', sortOrder: 3, parentCode: 'MCGILL' },
  { categoryKey: 'COURSE_PROGRAM', name: 'Data Analytics', code: 'DA', sortOrder: 4, parentCode: 'UBC' },
  { categoryKey: 'COURSE_PROGRAM', name: 'International Business', code: 'IB', sortOrder: 5, parentCode: 'UOM' },
  { categoryKey: 'STUDY_LEVEL', name: 'Undergraduate', code: 'UG', sortOrder: 1 },
  { categoryKey: 'STUDY_LEVEL', name: 'Postgraduate', code: 'PG', sortOrder: 2 },
  { categoryKey: 'STUDY_LEVEL', name: 'Diploma', code: 'DIPLOMA', sortOrder: 3 },
  { categoryKey: 'STUDY_LEVEL', name: 'Foundation', code: 'FOUNDATION', sortOrder: 4 },
  { categoryKey: 'STUDY_PURPOSE', name: 'Higher Education', code: 'HIGHER_ED', sortOrder: 1 },
  { categoryKey: 'STUDY_PURPOSE', name: 'Career Opportunity', code: 'CAREER', sortOrder: 2 },
  { categoryKey: 'STUDY_PURPOSE', name: 'Research', code: 'RESEARCH', sortOrder: 3 },
  { categoryKey: 'STUDY_PURPOSE', name: 'Career Change', code: 'CAREER_CHANGE', sortOrder: 4 },
  { categoryKey: 'STUDY_PURPOSE', name: 'Personal Development', code: 'PERSONAL', sortOrder: 5 },
  { categoryKey: 'STUDY_PURPOSE', name: 'Other', code: 'OTHER', sortOrder: 6 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Study Abroad', code: 'STUDY_ABROAD', sortOrder: 1 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Language Prep', code: 'LANGUAGE', sortOrder: 2 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Admission', code: 'ADMISSION', sortOrder: 3 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Application', code: 'APPLICATION', sortOrder: 4 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Documentation', code: 'DOCUMENTATION', sortOrder: 5 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Visa', code: 'VISA', sortOrder: 6 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Scholarship', code: 'SCHOLARSHIP', sortOrder: 7 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Accommodation', code: 'ACCOMMODATION', sortOrder: 8 },
  { categoryKey: 'SERVICE_CATEGORY', name: 'Other', code: 'OTHER', sortOrder: 9 },
  { categoryKey: 'SERVICE_TYPE', name: 'University Application', code: 'UNI_APP', sortOrder: 1, parentCode: 'STUDY_ABROAD' },
  { categoryKey: 'SERVICE_TYPE', name: 'Visa Processing', code: 'VISA', sortOrder: 2, parentCode: 'STUDY_ABROAD' },
  { categoryKey: 'SERVICE_TYPE', name: 'Counselling', code: 'COUNSELLING', sortOrder: 3, parentCode: 'STUDY_ABROAD' },
  { categoryKey: 'SERVICE_TYPE', name: 'IELTS Coaching', code: 'IELTS', sortOrder: 4, parentCode: 'LANGUAGE' },
  { categoryKey: 'PACKAGE_TYPE', name: 'Standard', code: 'STANDARD', sortOrder: 1 },
  { categoryKey: 'PACKAGE_TYPE', name: 'Premium', code: 'PREMIUM', sortOrder: 2 },
  { categoryKey: 'PACKAGE_TYPE', name: 'VIP', code: 'VIP', sortOrder: 3 },
  { categoryKey: 'CHARGE_TYPE', name: 'File Opening Charge', code: 'FILE_OPENING', sortOrder: 1 },
  { categoryKey: 'CHARGE_TYPE', name: 'Service Charge', code: 'SERVICE', sortOrder: 2 },
  { categoryKey: 'CHARGE_TYPE', name: 'Application Fee', code: 'APP_FEE', sortOrder: 3 },
  { categoryKey: 'DISCOUNT_TYPE', name: 'Percentage', code: 'PERCENT', sortOrder: 1 },
  { categoryKey: 'DISCOUNT_TYPE', name: 'Fixed', code: 'FIXED', sortOrder: 2 },
  { categoryKey: 'DISCOUNT_TYPE', name: 'Early Bird', code: 'EARLY_BIRD', sortOrder: 3 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Call', code: 'CALL', sortOrder: 1 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'WhatsApp', code: 'WHATSAPP', sortOrder: 2 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Email', code: 'EMAIL', sortOrder: 3 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Meeting', code: 'MEETING', sortOrder: 4 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Counselling', code: 'COUNSELLING', sortOrder: 5 },
  { categoryKey: 'ACTIVITY_TYPE', name: 'Note', code: 'NOTE', sortOrder: 6 },
  {
    categoryKey: 'CONVERSATION_CHANNEL',
    name: 'No channel',
    code: 'NONE',
    sortOrder: 1,
    description: 'No communication channel',
    extras: { icon: 'fa-solid fa-ban', activityType: 'OTHER' },
  },
  {
    categoryKey: 'CONVERSATION_CHANNEL',
    name: 'Call',
    code: 'CALL',
    sortOrder: 2,
    description: 'Phone call',
    extras: { icon: 'fa-solid fa-phone', activityType: 'CALL' },
  },
  {
    categoryKey: 'CONVERSATION_CHANNEL',
    name: 'WhatsApp',
    code: 'WHATSAPP',
    sortOrder: 3,
    description: 'WhatsApp message',
    extras: { icon: 'fa-brands fa-whatsapp', activityType: 'WHATSAPP' },
  },
  {
    categoryKey: 'CONVERSATION_CHANNEL',
    name: 'Email',
    code: 'EMAIL',
    sortOrder: 4,
    description: 'Email conversation',
    extras: { icon: 'fa-solid fa-envelope', activityType: 'EMAIL' },
  },
  {
    categoryKey: 'CONVERSATION_CHANNEL',
    name: 'SMS',
    code: 'SMS',
    sortOrder: 5,
    description: 'SMS / text message',
    extras: { icon: 'fa-solid fa-comment-sms', activityType: 'SMS' },
  },
  {
    categoryKey: 'CONVERSATION_CHANNEL',
    name: 'In-person',
    code: 'IN_PERSON',
    sortOrder: 6,
    description: 'In-person meeting',
    extras: { icon: 'fa-solid fa-user', activityType: 'MEETING' },
  },
  {
    categoryKey: 'CONVERSATION_CHANNEL',
    name: 'Meeting',
    code: 'MEETING',
    sortOrder: 7,
    description: 'Scheduled meeting',
    extras: { icon: 'fa-solid fa-comments', activityType: 'MEETING' },
  },
  {
    categoryKey: 'CONVERSATION_CHANNEL',
    name: 'Note',
    code: 'NOTE',
    sortOrder: 8,
    description: 'Internal note',
    extras: { icon: 'fa-solid fa-clipboard', activityType: 'OTHER' },
  },
  {
    categoryKey: 'CONVERSATION_CHANNEL',
    name: 'Other',
    code: 'OTHER',
    sortOrder: 9,
    description: 'Other channel',
    extras: { icon: 'fa-solid fa-ellipsis', activityType: 'OTHER' },
  },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Call', code: 'CALL', sortOrder: 1 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'WhatsApp', code: 'WHATSAPP', sortOrder: 2 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Email', code: 'EMAIL', sortOrder: 3 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Meeting', code: 'MEETING', sortOrder: 4 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Document Collection', code: 'DOCUMENTS', sortOrder: 5 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Payment Follow-up', code: 'PAYMENT', sortOrder: 6 },
  { categoryKey: 'FOLLOW_UP_TYPE', name: 'Counselling Follow-up', code: 'COUNSELLING', sortOrder: 7 },
  { categoryKey: 'CONTACT_METHOD', name: 'Phone', code: 'PHONE', sortOrder: 1 },
  { categoryKey: 'CONTACT_METHOD', name: 'WhatsApp', code: 'WHATSAPP', sortOrder: 2 },
  { categoryKey: 'CONTACT_METHOD', name: 'Email', code: 'EMAIL', sortOrder: 3 },
  { categoryKey: 'CONTACT_METHOD', name: 'In Person', code: 'IN_PERSON', sortOrder: 4 },
  { categoryKey: 'CONTACT_METHOD', name: 'Any', code: 'ANY', sortOrder: 5 },
  { categoryKey: 'CONTACT_TIME', name: 'Morning', code: 'MORNING', sortOrder: 1 },
  { categoryKey: 'CONTACT_TIME', name: 'Afternoon', code: 'AFTERNOON', sortOrder: 2 },
  { categoryKey: 'CONTACT_TIME', name: 'Evening', code: 'EVENING', sortOrder: 3 },
  { categoryKey: 'CONTACT_TIME', name: 'Specific Time', code: 'SPECIFIC', sortOrder: 4 },
  { categoryKey: 'CONTACT_RESULT', name: 'Connected', code: 'CONNECTED', sortOrder: 1 },
  { categoryKey: 'CONTACT_RESULT', name: 'No Answer', code: 'NO_ANSWER', sortOrder: 2 },
  { categoryKey: 'CONTACT_RESULT', name: 'Interested', code: 'INTERESTED', sortOrder: 3 },
  { categoryKey: 'CONTACT_RESULT', name: 'Call Back Later', code: 'CALLBACK', sortOrder: 4 },
  { categoryKey: 'CONTACT_RESULT', name: 'Not Interested', code: 'NOT_INTERESTED', sortOrder: 5 },
  { categoryKey: 'CONTACT_RESULT', name: 'Wrong Number', code: 'WRONG_NUMBER', sortOrder: 6 },
  { categoryKey: 'DESIGNATION', name: 'Administrator', code: 'ADMINISTRATOR', sortOrder: 0, isSystem: true, description: 'Fixed system designation for root administrator' },
  { categoryKey: 'DESIGNATION', name: 'CEO', code: 'CEO', sortOrder: 1 },
  { categoryKey: 'DESIGNATION', name: 'Manager', code: 'MANAGER', sortOrder: 2 },
  { categoryKey: 'DESIGNATION', name: 'Counsellor', code: 'COUNSELLOR', sortOrder: 3 },
  { categoryKey: 'DESIGNATION', name: 'Call Executive', code: 'CALL_EXECUTIVE', sortOrder: 4 },
  { categoryKey: 'DESIGNATION', name: 'Team Lead', code: 'TEAM_LEAD', sortOrder: 5 },
  { categoryKey: 'EMPLOYMENT_TYPE', name: 'Full-time', code: 'FULL_TIME', sortOrder: 1 },
  { categoryKey: 'EMPLOYMENT_TYPE', name: 'Part-time', code: 'PART_TIME', sortOrder: 2 },
  { categoryKey: 'EMPLOYMENT_TYPE', name: 'Intern', code: 'INTERN', sortOrder: 3 },
  { categoryKey: 'EMPLOYMENT_TYPE', name: 'Contract', code: 'CONTRACT', sortOrder: 4 },
  { categoryKey: 'EMPLOYMENT_TYPE', name: 'Probationary', code: 'PROBATIONARY', sortOrder: 5 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'Active', code: 'ACTIVE', sortOrder: 1 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'Probation', code: 'PROBATION', sortOrder: 2 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'On Leave', code: 'ON_LEAVE', sortOrder: 3 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'Inactive', code: 'INACTIVE', sortOrder: 4 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'Resigned', code: 'RESIGNED', sortOrder: 5 },
  { categoryKey: 'EMPLOYMENT_STATUS', name: 'Terminated', code: 'TERMINATED', sortOrder: 6 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Personal Documents', code: 'PERSONAL', sortOrder: 1 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Academic Documents', code: 'ACADEMIC', sortOrder: 2 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Language Documents', code: 'LANGUAGE', sortOrder: 3 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Financial Documents', code: 'FINANCIAL', sortOrder: 4 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Application Documents', code: 'APPLICATION', sortOrder: 5 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Professional', code: 'PROFESSIONAL', sortOrder: 6 },
  { categoryKey: 'DOCUMENT_CATEGORY', name: 'Other', code: 'OTHER', sortOrder: 7 },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Passport', code: 'PASSPORT', sortOrder: 1, parentCode: 'PERSONAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'NID', code: 'NID', sortOrder: 2, parentCode: 'PERSONAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Birth Certificate', code: 'BIRTH_CERTIFICATE', sortOrder: 3, parentCode: 'PERSONAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Photograph', code: 'PHOTOGRAPH', sortOrder: 4, parentCode: 'PERSONAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'SSC Certificate', code: 'SSC_CERTIFICATE', sortOrder: 10, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'SSC Transcript', code: 'SSC_TRANSCRIPT', sortOrder: 11, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'HSC Certificate', code: 'HSC_CERTIFICATE', sortOrder: 12, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'HSC Transcript', code: 'HSC_TRANSCRIPT', sortOrder: 13, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Diploma Certificate', code: 'DIPLOMA_CERTIFICATE', sortOrder: 14, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Bachelor Certificate', code: 'BACHELOR_CERTIFICATE', sortOrder: 15, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Bachelor Transcript', code: 'BACHELOR_TRANSCRIPT', sortOrder: 16, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Master Certificate', code: 'MASTER_CERTIFICATE', sortOrder: 17, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Master Transcript', code: 'MASTER_TRANSCRIPT', sortOrder: 18, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Transcript', code: 'TRANSCRIPT', sortOrder: 19, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Degree Certificate', code: 'DEGREE', sortOrder: 20, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'IELTS', code: 'IELTS', sortOrder: 30, parentCode: 'LANGUAGE' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'TOEFL', code: 'TOEFL', sortOrder: 31, parentCode: 'LANGUAGE' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'PTE', code: 'PTE', sortOrder: 32, parentCode: 'LANGUAGE' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Other Language Certificate', code: 'OTHER_LANGUAGE', sortOrder: 33, parentCode: 'LANGUAGE' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Bank Statement', code: 'BANK_STATEMENT', sortOrder: 40, parentCode: 'FINANCIAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Sponsor Document', code: 'SPONSOR', sortOrder: 41, parentCode: 'FINANCIAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Financial Certificate', code: 'FINANCIAL_CERTIFICATE', sortOrder: 42, parentCode: 'FINANCIAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'SOP', code: 'SOP', sortOrder: 50, parentCode: 'APPLICATION' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'CV', code: 'CV', sortOrder: 51, parentCode: 'APPLICATION' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Recommendation Letter', code: 'RECOMMENDATION', sortOrder: 52, parentCode: 'APPLICATION' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Application Form', code: 'APPLICATION_FORM', sortOrder: 53, parentCode: 'APPLICATION' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Offer Letter', code: 'OFFER', sortOrder: 54, parentCode: 'APPLICATION' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'CV', code: 'CV_PROFESSIONAL', sortOrder: 60, parentCode: 'PROFESSIONAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Experience Certificate', code: 'EXPERIENCE_CERTIFICATE', sortOrder: 61, parentCode: 'PROFESSIONAL' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Academic Certificate', code: 'ACADEMIC_CERTIFICATE', sortOrder: 21, parentCode: 'ACADEMIC' },
  { categoryKey: 'DOCUMENT_TYPE', name: 'Other Document', code: 'OTHER', sortOrder: 90, parentCode: 'OTHER' },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Pending', code: 'PENDING', sortOrder: 1 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Verified', code: 'VERIFIED', sortOrder: 2 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Rejected', code: 'REJECTED', sortOrder: 3 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Expired', code: 'EXPIRED', sortOrder: 4 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Replaced', code: 'REPLACED', sortOrder: 5 },
  { categoryKey: 'REJECTION_REASON', name: 'Unclear Scan', code: 'UNCLEAR', sortOrder: 1 },
  { categoryKey: 'REJECTION_REASON', name: 'Expired Document', code: 'EXPIRED', sortOrder: 2 },
  { categoryKey: 'REJECTION_REASON', name: 'Name Mismatch', code: 'NAME_MISMATCH', sortOrder: 3 },
  { categoryKey: 'REJECTION_REASON', name: 'Incomplete Document', code: 'INCOMPLETE', sortOrder: 4 },
  { categoryKey: 'REJECTION_REASON', name: 'Uploaded document is unclear', code: 'UNCLEAR_DOCUMENT', sortOrder: 5 },
  { categoryKey: 'REJECTION_REASON', name: 'Blurry', code: 'BLURRY', sortOrder: 6 },
  { categoryKey: 'REJECTION_REASON', name: 'Wrong Document', code: 'WRONG_DOCUMENT', sortOrder: 7 },
  { categoryKey: 'REJECTION_REASON', name: 'Incorrect Information', code: 'INCORRECT_INFORMATION', sortOrder: 8 },
  { categoryKey: 'REJECTION_REASON', name: 'Missing Page', code: 'MISSING_PAGE', sortOrder: 9 },
  { categoryKey: 'REJECTION_REASON', name: 'Invalid Copy', code: 'INVALID_COPY', sortOrder: 10 },
  { categoryKey: 'REJECTION_REASON', name: 'Other', code: 'OTHER', sortOrder: 11 },
  { categoryKey: 'DOCUMENT_REQUEST_METHOD', name: 'WhatsApp', code: 'WHATSAPP', sortOrder: 1 },
  { categoryKey: 'DOCUMENT_REQUEST_METHOD', name: 'Email', code: 'EMAIL', sortOrder: 2 },
  { categoryKey: 'DOCUMENT_REQUEST_METHOD', name: 'Phone', code: 'PHONE', sortOrder: 3 },
  { categoryKey: 'DOCUMENT_REQUEST_METHOD', name: 'In Person', code: 'IN_PERSON', sortOrder: 4 },
  { categoryKey: 'DOCUMENT_REQUEST_METHOD', name: 'Other', code: 'OTHER', sortOrder: 5 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Not Requested', code: 'NOT_REQUESTED', sortOrder: 10 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Requested', code: 'REQUESTED', sortOrder: 11 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Received', code: 'RECEIVED', sortOrder: 12 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Under Review', code: 'UNDER_REVIEW', sortOrder: 13 },
  { categoryKey: 'DOCUMENT_STATUS', name: 'Re-upload Required', code: 'REUPLOAD_REQUIRED', sortOrder: 14 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Cash', code: 'CASH', sortOrder: 1 },
  { categoryKey: 'PAYMENT_METHOD', name: 'bKash', code: 'BKASH', sortOrder: 2 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Nagad', code: 'NAGAD', sortOrder: 3 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Bank Transfer', code: 'BANK', sortOrder: 4 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Card', code: 'CARD', sortOrder: 5 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Online Payment', code: 'ONLINE', sortOrder: 6 },
  { categoryKey: 'PAYMENT_METHOD', name: 'Other', code: 'OTHER', sortOrder: 7 },
  { categoryKey: 'PAYMENT_TYPE', name: 'File Opening Charge', code: 'FILE_OPENING', sortOrder: 1 },
  { categoryKey: 'PAYMENT_TYPE', name: 'Service Charge', code: 'SERVICE', sortOrder: 2 },
  { categoryKey: 'PAYMENT_TYPE', name: 'Additional Service', code: 'ADDITIONAL', sortOrder: 3 },
  { categoryKey: 'PAYMENT_TYPE', name: 'Custom Charge', code: 'CUSTOM', sortOrder: 4 },
  { categoryKey: 'PAYMENT_STATUS', name: 'Pending', code: 'PENDING', sortOrder: 1 },
  { categoryKey: 'PAYMENT_STATUS', name: 'Paid', code: 'PAID', sortOrder: 2 },
  { categoryKey: 'PAYMENT_STATUS', name: 'Partial', code: 'PARTIAL', sortOrder: 3 },
  { categoryKey: 'PAYMENT_STATUS', name: 'Refunded', code: 'REFUNDED', sortOrder: 4 },
  { categoryKey: 'REFUND_REASON', name: 'Service Cancelled', code: 'CANCELLED', sortOrder: 1 },
  { categoryKey: 'REFUND_REASON', name: 'Duplicate Payment', code: 'DUPLICATE', sortOrder: 2 },
  { categoryKey: 'REFUND_REASON', name: 'Overpayment', code: 'OVERPAYMENT', sortOrder: 3 },
]

export function getMasterDataCategory(key: string) {
  return MASTER_DATA_CATEGORY_MAP.get(key)
}
