export const PERMISSION_CATALOG = [
  { module: 'Lead Management', resource: 'lead', action: 'view', description: 'View leads' },
  { module: 'Lead Management', resource: 'lead', action: 'create', description: 'Create leads' },
  { module: 'Lead Management', resource: 'lead', action: 'edit', description: 'Edit leads' },
  { module: 'Lead Management', resource: 'lead', action: 'delete', description: 'Delete leads' },
  { module: 'Lead Management', resource: 'lead', action: 'assign', description: 'Assign leads' },
  { module: 'Lead Management', resource: 'lead', action: 'reassign', description: 'Reassign leads' },
  { module: 'Lead Management', resource: 'lead', action: 'handover', description: 'Hand a qualified lead over to a counsellor' },
  { module: 'Lead Management', resource: 'lead', action: 'convert', description: 'Convert leads' },
  { module: 'Lead Management', resource: 'lead', action: 'export', description: 'Export leads' },
  { module: 'Lead Management', resource: 'lead', action: 'create_duplicate', description: 'Create a lead even when a duplicate phone exists' },
  { module: 'Lead Management', resource: 'lead', action: 'qualify', description: 'Record lead qualification result' },
  { module: 'Lead Management', resource: 'lead', action: 'override_priority', description: 'Manually override lead priority' },
  { module: 'Lead Management', resource: 'lead', action: 'update_status', description: 'Change lead status' },
  { module: 'Lead Management', resource: 'lead', action: 'override_status', description: 'Override required lead status transitions' },
  { module: 'Lead Management', resource: 'lead', action: 'close', description: 'Mark a lead as Lost, Closed, Duplicate, or Invalid' },
  { module: 'Lead Management', resource: 'lead', action: 'reopen', description: 'Reopen a lead from a terminal status' },
  { module: 'Lead Management', resource: 'lead', action: 'change_source', description: 'Correct a lead source or campaign after creation' },
  { module: 'Follow-up', resource: 'follow_up', action: 'view', description: 'View follow-ups' },
  { module: 'Follow-up', resource: 'follow_up', action: 'create', description: 'Create follow-ups' },
  { module: 'Follow-up', resource: 'follow_up', action: 'edit', description: 'Edit follow-ups' },
  { module: 'Follow-up', resource: 'follow_up', action: 'delete', description: 'Delete follow-ups' },
  { module: 'Activities', resource: 'activity', action: 'view', description: 'View activities' },
  { module: 'Activities', resource: 'activity', action: 'create', description: 'Create activities' },
  { module: 'Activities', resource: 'activity', action: 'edit', description: 'Edit activities' },
  { module: 'Activities', resource: 'activity', action: 'delete', description: 'Delete activities' },
  { module: 'Service & Package', resource: 'service', action: 'view', description: 'View services' },
  { module: 'Service & Package', resource: 'service', action: 'create', description: 'Create services' },
  { module: 'Service & Package', resource: 'service', action: 'edit', description: 'Edit services' },
  { module: 'Service & Package', resource: 'service', action: 'deactivate', description: 'Activate or deactivate services' },
  { module: 'Service & Package', resource: 'service', action: 'configure', description: 'Configure packages' },
  { module: 'Service & Package', resource: 'service', action: 'custom_charge', description: 'Create custom charges' },
  { module: 'Service & Package', resource: 'service', action: 'discount', description: 'Apply discounts' },
  { module: 'Service & Package', resource: 'service', action: 'offer', description: 'Create offers' },
  { module: 'Payment', resource: 'payment', action: 'view', description: 'View payments' },
  { module: 'Payment', resource: 'payment', action: 'create', description: 'Create payments' },
  { module: 'Payment', resource: 'payment', action: 'edit', description: 'Edit payments' },
  { module: 'Payment', resource: 'payment', action: 'cancel', description: 'Cancel payments' },
  { module: 'Payment', resource: 'payment', action: 'delete', description: 'Delete payments' },
  { module: 'Payment', resource: 'payment', action: 'approve', description: 'Approve payment adjustments' },
  { module: 'Receipt', resource: 'receipt', action: 'view', description: 'View receipts' },
  { module: 'Receipt', resource: 'receipt', action: 'generate', description: 'Generate receipts' },
  { module: 'Receipt', resource: 'receipt', action: 'download', description: 'Download receipts' },
  { module: 'Receipt', resource: 'receipt', action: 'delete', description: 'Delete receipts' },
  { module: 'Documents', resource: 'document', action: 'view', description: 'View documents' },
  { module: 'Documents', resource: 'document', action: 'upload', description: 'Upload documents' },
  { module: 'Documents', resource: 'document', action: 'verify', description: 'Verify documents' },
  { module: 'Documents', resource: 'document', action: 'download', description: 'Download documents' },
  { module: 'Documents', resource: 'document', action: 'delete', description: 'Delete documents' },
  { module: 'Reports', resource: 'report', action: 'view', description: 'View reports' },
  { module: 'Reports', resource: 'report', action: 'export', description: 'Export reports' },
  { module: 'Employee Management', resource: 'employee', action: 'view', description: 'View employees' },
  { module: 'Employee Management', resource: 'employee', action: 'create', description: 'Create employees' },
  { module: 'Employee Management', resource: 'employee', action: 'edit', description: 'Edit employees' },
  { module: 'Employee Management', resource: 'employee', action: 'delete', description: 'Delete employees' },
  { module: 'Employee Performance', resource: 'employee_performance', action: 'view', description: 'View employee performance' },
  { module: 'Notifications', resource: 'notification', action: 'view', description: 'View notifications' },
  { module: 'Notifications', resource: 'notification', action: 'configure', description: 'Configure notifications' },
  { module: 'Integrations', resource: 'integration', action: 'view', description: 'View integrations' },
  { module: 'Integrations', resource: 'integration', action: 'configure', description: 'Configure integrations' },
  { module: 'Communication Hub', resource: 'communication', action: 'view', description: 'View Communication Hub and history' },
  { module: 'Communication Hub', resource: 'communication', action: 'reprocess', description: 'Reprocess failed communications' },
  { module: 'Campaigns', resource: 'campaign', action: 'view', description: 'View campaigns and attribution' },
  { module: 'Campaigns', resource: 'campaign', action: 'manage', description: 'Create and update campaigns' },
  { module: 'User Management', resource: 'user', action: 'view', description: 'View users' },
  { module: 'User Management', resource: 'user', action: 'create', description: 'Create users' },
  { module: 'User Management', resource: 'user', action: 'edit', description: 'Edit users' },
  { module: 'User Management', resource: 'user', action: 'delete', description: 'Delete users' },
  { module: 'User Management', resource: 'user', action: 'configure', description: 'Manage sessions, status, and password reset' },
  { module: 'Role & Permission', resource: 'role', action: 'view', description: 'View roles' },
  { module: 'Role & Permission', resource: 'role', action: 'create', description: 'Create roles' },
  { module: 'Role & Permission', resource: 'role', action: 'edit', description: 'Edit roles' },
  { module: 'Role & Permission', resource: 'role', action: 'delete', description: 'Delete roles' },
  { module: 'Role & Permission', resource: 'permission', action: 'view', description: 'View permissions' },
  { module: 'Role & Permission', resource: 'permission', action: 'configure', description: 'Configure permissions and overrides' },
  { module: 'Master Data', resource: 'master_data', action: 'view', description: 'View master data' },
  { module: 'Master Data', resource: 'master_data', action: 'create', description: 'Create master data' },
  { module: 'Master Data', resource: 'master_data', action: 'edit', description: 'Edit master data' },
  { module: 'Master Data', resource: 'master_data', action: 'delete', description: 'Delete master data' },
  { module: 'Settings', resource: 'settings', action: 'view', description: 'View settings' },
  { module: 'Settings', resource: 'settings', action: 'configure', description: 'Configure settings' },
  { module: 'Audit Log', resource: 'audit', action: 'view', description: 'View audit logs' },
] as const

export const SCOPE_RESOURCES = ['lead', 'document', 'employee_performance'] as const

export type PermissionKey = `${(typeof PERMISSION_CATALOG)[number]['resource']}:${(typeof PERMISSION_CATALOG)[number]['action']}`

export const ROLE_DEFAULTS: Record<
  string,
  {
    name: string
    description: string
    isSystem?: boolean
    permissions: readonly string[] | 'all'
    scopes: Record<(typeof SCOPE_RESOURCES)[number], 'OWN' | 'TEAM' | 'DEPARTMENT' | 'ALL'>
  }
> = {
  admin: {
    name: 'Administrator',
    description: 'Fixed system administrator role with full access',
    isSystem: true,
    permissions: 'all',
    scopes: { lead: 'ALL', document: 'ALL', employee_performance: 'ALL' },
  },
  ceo: {
    name: 'CEO',
    description: 'Organization-level business visibility',
    permissions: [
      'lead:view',
      'lead:export',
      'follow_up:view',
      'activity:view',
      'service:view',
      'payment:view',
      'receipt:view',
      'document:view',
      'document:download',
      'report:view',
      'report:export',
      'employee:view',
      'employee_performance:view',
      'notification:view',
      'integration:view',
      'communication:view',
      'campaign:view',
      'user:view',
      'role:view',
      'permission:view',
      'master_data:view',
      'settings:view',
      'audit:view',
    ],
    scopes: { lead: 'ALL', document: 'ALL', employee_performance: 'ALL' },
  },
  manager: {
    name: 'Manager',
    description: 'Team-scoped lead and employee management',
    permissions: [
      'lead:view',
      'lead:create',
      'lead:edit',
      'lead:assign',
      'lead:reassign',
      'lead:handover',
      'lead:convert',
      'lead:export',
      'lead:create_duplicate',
      'lead:qualify',
      'lead:override_priority',
      'lead:update_status',
      'lead:override_status',
      'lead:close',
      'lead:reopen',
      'follow_up:view',
      'follow_up:create',
      'follow_up:edit',
      'follow_up:delete',
      'activity:view',
      'activity:create',
      'activity:edit',
      'service:view',
      'payment:view',
      'receipt:view',
      'receipt:download',
      'document:view',
      'document:upload',
      'document:verify',
      'document:download',
      'report:view',
      'employee:view',
      'employee:create',
      'employee:edit',
      'employee_performance:view',
      'notification:view',
      'communication:view',
      'communication:reprocess',
      'campaign:view',
      'campaign:manage',
      'user:view',
      'audit:view',
      'master_data:view',
    ],
    scopes: { lead: 'TEAM', document: 'TEAM', employee_performance: 'TEAM' },
  },
  counsellor: {
    name: 'Counsellor',
    description: 'Assigned-lead and counselling access',
    permissions: [
      'lead:view',
      'lead:create',
      'lead:edit',
      'lead:convert',
      'lead:qualify',
      'lead:update_status',
      'lead:close',
      'lead:reopen',
      'follow_up:view',
      'follow_up:create',
      'follow_up:edit',
      'follow_up:delete',
      'activity:view',
      'activity:create',
      'activity:edit',
      'service:view',
      'payment:view',
      'document:view',
      'document:upload',
      'document:verify',
      'employee_performance:view',
      'notification:view',
      'communication:view',
      'campaign:view',
      'audit:view',
    ],
    scopes: { lead: 'OWN', document: 'OWN', employee_performance: 'OWN' },
  },
  marketing_manager: {
    name: 'Marketing Manager',
    description: 'Campaign lead visibility and marketing performance',
    permissions: [
      'lead:view',
      'follow_up:view',
      'activity:view',
      'report:view',
      'notification:view',
      'communication:view',
      'campaign:view',
    ],
    scopes: { lead: 'ALL', document: 'OWN', employee_performance: 'OWN' },
  },
  call_executive: {
    name: 'Call Executive',
    description: 'Lead handling, calling, and follow-up access',
    permissions: [
      'lead:view',
      'lead:create',
      'lead:edit',
      'lead:handover',
      'lead:update_status',
      'lead:close',
      'lead:reopen',
      'follow_up:view',
      'follow_up:create',
      'follow_up:edit',
      'activity:view',
      'activity:create',
      'document:view',
      'document:upload',
      'notification:view',
      'communication:view',
      'campaign:view',
      'audit:view',
    ],
    scopes: { lead: 'OWN', document: 'OWN', employee_performance: 'OWN' },
  },
}

export function permissionKey(resource: string, action: string) {
  return `${resource}:${action}`
}
