export type NotificationPriority = "Normal" | "Important" | "Critical";
export type RecipientRule = "owner" | "owner_manager" | "admin";

export type NotificationEventDefinition = {
  eventType: string;
  label: string;
  description: string;
  enabled: boolean;
  mandatory: boolean;
  priority: NotificationPriority;
  inApp: boolean;
  email: boolean;
  whatsapp: boolean;
  browser: boolean;
  recipientRule: RecipientRule;
  notifyPreviousOwner: boolean;
  overdueAfterMinutes: number;
  statusAllowlist: string[] | null;
};

export const NOTIFICATION_EVENTS: NotificationEventDefinition[] = [
  {
    eventType: "lead_assigned",
    label: "New Lead Assigned",
    description: "Sent when a lead is assigned to an employee.",
    enabled: true,
    mandatory: true,
    priority: "Important",
    inApp: true,
    email: true,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "lead_reassigned",
    label: "Lead Reassigned",
    description: "Sent when a lead moves to a new owner.",
    enabled: true,
    mandatory: true,
    priority: "Important",
    inApp: true,
    email: true,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "follow_up_reminder",
    label: "Follow-up Reminder",
    description: "Advance reminder before a scheduled follow-up.",
    enabled: true,
    mandatory: false,
    priority: "Normal",
    inApp: true,
    email: false,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "counselling_reminder",
    label: "Counselling Reminder",
    description: "Advance reminder before a counselling session.",
    enabled: true,
    mandatory: false,
    priority: "Normal",
    inApp: true,
    email: false,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "meeting_reminder",
    label: "Meeting Reminder",
    description: "Advance reminder before a meeting with a lead.",
    enabled: true,
    mandatory: false,
    priority: "Normal",
    inApp: true,
    email: false,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "follow_up_due",
    label: "Follow-up Due",
    description: "Sent when a follow-up's scheduled time arrives.",
    enabled: true,
    mandatory: false,
    priority: "Important",
    inApp: true,
    email: false,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "follow_up_overdue",
    label: "Overdue Follow-up",
    description: "Sent once after a follow-up stays incomplete past its due time.",
    enabled: true,
    mandatory: false,
    priority: "Important",
    inApp: true,
    email: true,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 60,
    statusAllowlist: null,
  },
  {
    eventType: "service_offer_created",
    label: "Service Offer Created",
    description: "Sent when a service offer is generated.",
    enabled: true,
    mandatory: false,
    priority: "Normal",
    inApp: true,
    email: true,
    whatsapp: false,
    browser: false,
    recipientRule: "owner_manager",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "service_offer_accepted",
    label: "Service Offer Accepted",
    description: "Sent to the lead owner when an offer is accepted.",
    enabled: true,
    mandatory: false,
    priority: "Important",
    inApp: true,
    email: true,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "payment_received",
    label: "Payment Received",
    description: "Sent when a payment is recorded successfully.",
    enabled: true,
    mandatory: false,
    priority: "Important",
    inApp: true,
    email: false,
    whatsapp: false,
    browser: false,
    recipientRule: "owner_manager",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "payment_failed",
    label: "Payment Failed",
    description: "Sent when a payment is recorded as failed.",
    enabled: true,
    mandatory: false,
    priority: "Critical",
    inApp: true,
    email: true,
    whatsapp: false,
    browser: false,
    recipientRule: "owner_manager",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "file_opened",
    label: "File Opened",
    description: "Sent when a lead file is opened.",
    enabled: true,
    mandatory: false,
    priority: "Normal",
    inApp: true,
    email: false,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "lead_status_updated",
    label: "Lead Status Updated",
    description: "Sent only for configured significant status changes.",
    enabled: true,
    mandatory: false,
    priority: "Normal",
    inApp: true,
    email: false,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: ["CONVERTED"],
  },
  {
    eventType: "lead_priority_updated",
    label: "Lead Priority Updated",
    description: "Sent when a lead priority changes.",
    enabled: true,
    mandatory: false,
    priority: "Normal",
    inApp: true,
    email: false,
    whatsapp: false,
    browser: false,
    recipientRule: "owner",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "high_priority_lead",
    label: "High Priority Lead",
    description: "Sent when a lead is marked High Priority.",
    enabled: true,
    mandatory: false,
    priority: "Important",
    inApp: true,
    email: true,
    whatsapp: false,
    browser: false,
    recipientRule: "owner_manager",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
  {
    eventType: "permission_change",
    label: "Security / Permission Alert",
    description: "Sent when critical permissions change.",
    enabled: true,
    mandatory: true,
    priority: "Critical",
    inApp: true,
    email: true,
    whatsapp: false,
    browser: true,
    recipientRule: "admin",
    notifyPreviousOwner: false,
    overdueAfterMinutes: 0,
    statusAllowlist: null,
  },
];

export function eventDefinition(eventType: string) {
  return NOTIFICATION_EVENTS.find((item) => item.eventType === eventType) || null;
}
